version: '3.8'
services:
  aq54-db:
    environment:
      POSTGRES_DB: aq54-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    container_name: aq54-db
    hostname: aq54-db
    build:
      context: .
      dockerfile: ./Dockerfile.db
    ports:
      - '5432:5432'

  aq54-backend:
    container_name: aq54-backend
    hostname: aq54-backend
    build: 
      context: ./aq54-backend
      dockerfile: Dockerfile
    ports:
      - '${API_LISTEN_PORT}:${API_LISTEN_PORT}'
    environment:
      - NODE_ENV=prod
      - API_PORT=${API_LISTEN_PORT}
      - API_VERSION=1.0.0
      - DB_URL=postgresql://${DB_USER}:${DB_PASSWORD}@aq54-db:5432/aq54-db
      - FB_ACCOUNT_TYPE=${FB_ACCOUNT_TYPE}
      - FB_PROJECT_ID=${FB_PROJECT_ID}
      - FB_PRIVATE_KEY_ID=${FB_PRIVATE_KEY_ID}
      - FB_PRIVATE_KEY=${FB_PRIVATE_KEY}
      - FB_CLIENT_EMAIL=${FB_CLIENT_EMAIL}
      - FB_CLIENT_ID=${FB_CLIENT_ID}
      - FB_AUTH_URI=${FB_AUTH_URI}
      - FB_TOKEN_URI=${FB_TOKEN_URI}
      - FB_AUTH_PROVIDER_X509=${FB_AUTH_PROVIDER_X509}
      - FB_CLIENT_X509=${FB_CLIENT_X509}
      - FB_UNIVERSE_DOMAIN=${FB_UNIVERSE_DOMAIN}
    depends_on:
      - aq54-db

  aq54-frontend:
    container_name: aq54-frontend
    build: 
      context: ./aq54
      dockerfile: Dockerfile
      args:
        NODE_ENV: prod
        PORT: ${API_LISTEN_PORT}
        REACT_APP_API_HOST: http://localhost
        REACT_APP_API_PORT: ${API_LISTEN_PORT}
        REACT_APP_MAPBOX_TOKEN: ${MAPBOX_TOKEN}
        REACT_APP_FIREBASE_API_KEY: ${FB_API_KEY}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${FB_AUTH_DOMAIN}
        REACT_APP_FIREBASE_PROJECT_ID: ${FB_PROJECT_ID}
        REACT_APP_FIREBASE_STORAGE_BUCKET: ${FB_STORAGE_BUCKET}
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${FB_MESSAGING_SENDER_ID}
        REACT_APP_FIREBASE_APP_ID: ${FB_APP_ID}
        REACT_APP_FIREBASE_MEASUREMENT_ID: ${FB_MEASUREMENT_ID}
    ports:
      - '${FRONTEND_LISTEN_PORT}:80'
    environment:
      - NODE_ENV=prod
      - PORT=${API_LISTEN_PORT}
      - REACT_APP_API_HOST=aq54-backend
      - REACT_APP_API_PORT=${API_LISTEN_PORT}
      - REACT_APP_MAPBOX_TOKEN=${MAPBOX_TOKEN}
      - REACT_APP_FIREBASE_API_KEY=${FB_API_KEY}
      - REACT_APP_FIREBASE_AUTH_DOMAIN=${FB_AUTH_DOMAIN}
      - REACT_APP_FIREBASE_PROJECT_ID=${FB_PROJECT_ID}
      - REACT_APP_FIREBASE_STORAGE_BUCKET=${FB_STORAGE_BUCKET}
      - REACT_APP_FIREBASE_MESSAGING_SENDER_ID=${FB_MESSAGING_SENDER_ID}
      - REACT_APP_FIREBASE_APP_ID=${FB_APP_ID}
      - REACT_APP_FIREBASE_MEASUREMENT_ID=${FB_MEASUREMENT_ID}
    depends_on:
      - aq54-backend